# Generated by Django 5.0.6 on 2026-05-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Název')),
                ('description', models.TextField(verbose_name='Popis')),
                ('type', models.CharField(choices=[('urgent', 'Havarijní'), ('info', 'Informace'), ('notice', 'Oznámení'), ('event', 'Akce')], default='info', max_length=20, verbose_name='Typ')),
                ('icon', models.CharField(default='info', max_length=50, verbose_name='Ikona (Material Symbols)')),
                ('date', models.CharField(blank=True, max_length=100, verbose_name='Datum')),
                ('time', models.CharField(blank=True, max_length=100, verbose_name='Čas')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Místo')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Příloha')),
                ('attachment_name', models.CharField(blank=True, max_length=200, verbose_name='Název přílohy')),
                ('attachment_size', models.CharField(blank=True, max_length=50, verbose_name='Velikost přílohy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Příspěvek',
                'verbose_name_plural': 'Příspěvky',
                'ordering': ['-created_at'],
            },
        ),
    ]
