# Generated by Django 5.0.6 on 2026-05-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nastenka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='icon',
            field=models.CharField(choices=[('Havarijní', [('emergency_home', 'Nouzová situace v domě'), ('warning', 'Varování'), ('water_damage', 'Poškození vodou'), ('plumbing', 'Instalatérství / voda'), ('electrical_services', 'Elektroinstalace'), ('local_fire_department', 'Požár / havarijní')]), ('Informace', [('info', 'Informace (obecná)'), ('lightbulb', 'Tip / doporučení'), ('announcement', 'Oznámení'), ('campaign', 'Důležitá zpráva'), ('payments', 'Platby / finance'), ('account_balance', 'Bankovní / hospodaření')]), ('Oznámení / Údržba', [('construction', 'Stavba / rekonstrukce'), ('build', 'Oprava / údržba'), ('handyman', 'Řemeslné práce'), ('delete_sweep', 'Úklid / odvoz odpadu'), ('elevator', 'Výtah'), ('lock', 'Zámek / přístup')]), ('Akce / Schůze', [('event', 'Akce'), ('calendar_month', 'Termín / kalendář'), ('meeting_room', 'Schůze / shromáždění'), ('gavel', 'Hlasování / usnesení'), ('description', 'Dokument / zápis'), ('groups', 'Setkání obyvatel')])], default='info', max_length=50, verbose_name='Ikona'),
        ),
    ]
